### PR TITLE
Update serde to 1.0 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Could you squash the commits?

**Comment by Eijebong** [comment]
Sure once servo is ready (I don't want to block servo's development by merging this too soon ^^)

**Comment by Eijebong** [comment]
Done !

**Comment by emilio** [comment]
Servo's ready, this should be ready to merge. r? @MortimerGoro 

Thanks!

**Comment by MortimerGoro** [comment]
Merged and 0.5 version published!

**Pull request merged**
